name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 1.0.3
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.0.0-nullsafety.2
  http: ^0.12.2
  equatable: ^2.0.0-nullsafety.0
  http_parser: ^4.0.0-nullsafety
  bloc: ^7.0.0-nullsafety.0
  flutter_bloc: ^7.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.2
  pedantic: ^1.10.0-nullsafety.2

# The following section is specific to Flutter.
flutter:
