name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 2.2.1
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  http_parser: ^4.0.2
  video_player: ^2.8.3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.3

flutter:
